# -*- coding: utf-8 -*-
"""IRIS FLOWER CLASSIFICATION .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YC9YdTr0h2d0q1swPZZjc9LgMmHRBUVH
"""

import numpy as np


import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv("/content/Iris (1).csv")

print(df)

df.head()

df.tail()

df.columns

df.describe()

df['SepalLengthCm']

projected_columns = ['PetalWidthCm', 'Species']
df[projected_columns]

df['Species'].value_counts()

input_features = ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']
df_input = df[input_features]
df_input

output_features = ['Species']
df_output = df[output_features]
df_output

a, b, c = [2, 4, 5]

df_input_train, df_input_test, df_output_train, df_output_test = train_test_split(df_input, df_output, test_size = 0.2)
df_input_train

model = KNeighborsClassifier()
model.fit(df_input_train, df_output_train)

predictions = model.predict(df_input_test)
predictions

df_output_test

accuracy_score(df_output_test, predictions)